### ISSUE TITLE
Prepare a k8s cluster on OCI free instances

### ISSUE THREAD

**Issue by bkielbasa** [golang-app/ecommerce-infra#10]
Heavily inspired by https://github.com/dansimone/kubernetes-the-hard-way-on-oci/

```[tasklist]
### Tasks
- [ ] Make sure that all instances are Always Free-eligible
- [ ] Generating the Data Encryption Config and Key
- [ ] Bootstrapping the etcd Cluster
- [ ] Bootstrapping the Kubernetes Control Plane
- [ ] Bootstrapping the Kubernetes Worker Nodes
- [ ] Configuring kubectl for Remote Access
- [ ] Provisioning Pod Network Routes
- [ ] Deploying the DNS Cluster Add-on
- [ ] Rebuild the loadbalancer to use a Compute instance instead of OCI-provider load balancer
```
